name: example

on:
  pull_request:
    paths:
      - ".github/workflows/example.yaml"
      - "example/lib/**"
      - "example/test/**"
      - "example/pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/example.yaml"
      - "example/lib/**"
      - "example/test/**"
      - "example/pubspec.yaml"

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: "example/"
